CREATE OR REPLACE FUNCTION public.random_questions (LIMIT_VALUE INT) RETURNS SETOF QUESTIONS AS $$
BEGIN
    RETURN QUERY SELECT * FROM QUESTIONS ORDER BY RANDOM() LIMIT LIMIT_VALUE;
END;
$$ LANGUAGE plpgsql;
